[book]
authors = ["Snehit Sah"]
language = "en"
multilingual = false
src = "src"
title = "Reference"

[output.html]
additional-js = ["mermaid-init.js"]
mathjax-support = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
